# Use root/example as user/password credentials
version: "3.1"

services:
  mongodb:
    image: mongo:latest
    container_name: "wiki-movies"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
