# Use root/example as user/password credentials
version: "3.1"

services:
  mongodb:
    image: mongo:latest
    container_name: "wiki-movies"
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
